name: Deploy CMNT Squad Tracker

on:
  push:
    branches: [ "main", "dev" ]
  workflow_run:
    workflows: ["Update players.json (dev nightly)"]
    types: [completed]

jobs:
  build-and-deploy:
    # Only run on successful updater runs, or any normal push
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      BRANCH: ${{ github.event_name == 'workflow_run'
        && github.event.workflow_run.head_branch
        || github.ref_name }}

      S3_BUCKET: ${{ (github.event_name == 'workflow_run'
        && github.event.workflow_run.head_branch == 'main')
        || github.ref == 'refs/heads/main'
        && 'cmnt-squad-tracker-goose'
        || 'cmnt-squad-tracker-goose-dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Build static site
        run: npm run build:static

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync files to S3
        run: aws s3 sync out/ s3://$S3_BUCKET --delete
