name: Deploy CMNT Squad Tracker

on:
  push:
    branches: [ "main", "dev" ]
  workflow_run:
    workflows: ["Update players.json (dev nightly)"]
    types: [completed]

jobs:
  build-and-deploy:
    # Only run on successful updater runs, or any normal push
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      BRANCH: ${{ github.event_name == 'workflow_run'
        && github.event.workflow_run.head_branch
        || github.ref_name }}

      S3_BUCKET: ${{ (github.event_name == 'workflow_run'
        && github.event.workflow_run.head_branch
